# Generated by Django 5.1.6 on 2025-03-05 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('admission_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=1)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='Profile Pictures/')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('RN', 'Rh Null')], max_length=4, null=True)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('transportation', models.CharField(blank=True, choices=[('SB', 'School Bus'), ('PV', 'Private'), ('PB', 'Public'), ('OF', 'On Foot')], max_length=2, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Disabled')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
