# Generated by Django 5.1.6 on 2025-03-16 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_enrollment_unique_together_and_more'),
        ('user', '0002_remove_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementstaff',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.schoolclass'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='academic.subject'),
        ),
    ]
