# Generated by Django 5.1.6 on 2025-03-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Disabled')], default='A', max_length=1),
        ),
    ]
