# Generated by Django 5.1.6 on 2025-03-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_managementstaff_staff_alter_teacher_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='social_twitter',
            new_name='social_instagram',
        ),
    ]
