# Generated by Django 5.1.6 on 2025-03-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_student_previous_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
    ]
