# Generated by Django 5.1.6 on 2025-03-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_social_twitter_staff_social_instagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementstaff',
            name='previous_workplace',
        ),
        migrations.RemoveField(
            model_name='managementstaff',
            name='previous_workplace_address',
        ),
        migrations.RemoveField(
            model_name='managementstaff',
            name='previous_workplace_phone_number',
        ),
        migrations.RemoveField(
            model_name='managementstaff',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='managementstaff',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='previous_school_address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='previous_school_phone_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teaching_experience',
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='previous_workplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='previous_workplace_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='previous_workplace_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
