# Generated by Django 5.1.6 on 2025-03-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='transportation',
            field=models.CharField(choices=[('SB', 'School Bus'), ('PV', 'Private'), ('PB', 'Public'), ('OF', 'On Foot')], max_length=2),
        ),
    ]
