# Generated by Django 5.1.6 on 2025-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_section_class_teacher'),
        ('user', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_class',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='academic.schoolclass'),
        ),
    ]
