# Generated by Django 5.1.6 on 2025-03-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_managementstaff_previous_workplace_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='date_of_join',
            new_name='date_of_joining',
        ),
    ]
