# Generated by Django 5.1.6 on 2025-04-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_teacher_school_class_teacher_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
