# Generated by Django 5.1.6 on 2025-03-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_parent_guardian_relation_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
