# Generated by Django 5.1.6 on 2025-03-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('T', 'Teacher'), ('M', 'Management')], default='T', max_length=1),
            preserve_default=False,
        ),
    ]
