# Generated by Django 5.1.6 on 2025-05-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='max_days',
            new_name='available_days',
        ),
    ]
