# Generated by Django 5.1.6 on 2025-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_parent_address_alter_parent_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
