# Generated by Django 5.1.6 on 2025-03-07 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_parent_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='user.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_of', to='user.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='user.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
    ]
