# Generated by Django 5.1.6 on 2025-03-11 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_subject_school_class'),
        ('user', '0007_staff_staff_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='school_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academic.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='academic.subject'),
        ),
    ]
