# Generated by Django 5.1.6 on 2025-05-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_leave_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='available_days',
        ),
        migrations.AddField(
            model_name='leave',
            name='total_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
