# Generated by Django 5.1.6 on 2025-03-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_teacher_school_class_remove_teacher_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
