# Generated by Django 5.1.3 on 2024-12-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
