# Generated by Django 5.1.3 on 2024-12-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_admission_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='employee_id',
        ),
    ]
