# Generated by Django 5.1.3 on 2024-12-31 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_guardian_address_alter_guardian_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousschool',
            name='attended_from',
        ),
        migrations.RemoveField(
            model_name='previousschool',
            name='attended_until',
        ),
    ]
