# Generated by Django 5.1.3 on 2025-01-01 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_enrollment_enrollment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_type',
            field=models.CharField(choices=[('m', 'Mother'), ('f', 'Father')], max_length=1, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
