# Generated by Django 5.1.6 on 2025-04-06 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='user.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.house'),
        ),
        migrations.AddField(
            model_name='routine',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='routine',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='user.teacher'),
        ),
        migrations.AddField(
            model_name='routine',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academic.schoolclass'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.schoolclass'),
        ),
        migrations.AddField(
            model_name='section',
            name='house',
            field=models.ManyToManyField(blank=True, related_name='sections', to='academic.house'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='academic.schoolclass'),
        ),
        migrations.AddField(
            model_name='routine',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academic.section'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.section'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academic.schoolclass'),
        ),
        migrations.AddField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academic.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('academic_year', 'school_class', 'section', 'roll_number')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('academic_year', 'day', 'start_time', 'school_class', 'section')},
        ),
    ]
