# Generated by Django 5.1.6 on 2025-03-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
