# Generated by Django 5.1.6 on 2025-03-06 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
