# Generated by Django 5.1.6 on 2025-03-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_academicyear_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
    ]
