# Generated by Django 5.1.6 on 2025-03-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_enrollment_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='end_date',
        ),
    ]
