# Generated by Django 5.1.6 on 2025-03-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_academicyear_is_active_alter_academicyear_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AlterField(
            model_name='section',
            name='houses',
            field=models.ManyToManyField(blank=True, null=True, to='academic.house'),
        ),
    ]
