# Generated by Django 5.1.6 on 2025-03-19 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_routine'),
        ('user', '0003_alter_managementstaff_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='academic_year',
            field=models.ForeignKey(default='377b2e9e-6dcd-4dc0-a94b-d2004f73776b', on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academic.academicyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routine',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='user.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('academic_year', 'day', 'start_time', 'school_class', 'section')},
        ),
    ]
