# Generated by Django 5.1.6 on 2025-04-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_section_class_teacher'),
        ('user', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together={('academic_year', 'day', 'start_time', 'school_class', 'section', 'subject', 'teacher')},
        ),
    ]
