# Generated by Django 5.1.6 on 2025-03-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_routine_academic_year_alter_routine_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academic.academicyear'),
        ),
    ]
