# Generated by Django 5.1.6 on 2025-03-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_section__class_alter_section_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academic.class'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('_class', 'name')},
        ),
    ]
