# Generated by Django 5.1.6 on 2025-03-07 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_remove_academicyear_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.house'),
        ),
    ]
