# Generated by Django 5.1.6 on 2025-03-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_section__class_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='houses',
            field=models.ManyToManyField(blank=True, to='academic.house'),
        ),
    ]
