# Generated by Django 5.1.6 on 2025-04-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_attendancesession_attendancerecord_delete_attendance'),
        ('user', '0003_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='user.teacher'),
        ),
    ]
