# Generated by Django 5.1.6 on 2025-03-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_section_houses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['_class', 'name']},
        ),
    ]
