# Generated by Django 5.1.6 on 2025-03-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_section_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='houses',
            field=models.ManyToManyField(blank=True, related_name='sections', to='academic.house'),
        ),
    ]
