# Generated by Django 5.1.6 on 2025-04-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_section_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.academicyear'),
        ),
    ]
