# Generated by Django 5.1.6 on 2025-04-27 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_assignment_status_chatmessage_chatattachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_access', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic.academicyear')),
                ('school_class', models.ManyToManyField(blank=True, related_name='announcements', to='academic.schoolclass')),
                ('section', models.ManyToManyField(blank=True, related_name='announcements', to='academic.section')),
            ],
        ),
    ]
