# Generated by Django 5.1.6 on 2025-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.CharField(choices=[('important', 'Important'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
    ]
