# Generated by Django 5.1.6 on 2025-05-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_onlinepaymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='section',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('unit', 'Unit Test')], default='midterm', max_length=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
