# Generated by Django 5.1.6 on 2025-05-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_remove_exam_duration_remove_exam_exam_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('terminal', 'Terminal Exam'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('unit', 'Unit Test')], default='midterm', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academic.schoolclass'),
        ),
    ]
