# Generated by Django 5.1.6 on 2025-05-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0018_alter_exam_exam_type_alter_exam_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='section',
        ),
    ]
