# Generated by Django 5.1.6 on 2025-05-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_remove_announcement_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='school_class',
        ),
        migrations.AddField(
            model_name='announcement',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academic.schoolclass'),
        ),
    ]
