# Generated by Django 5.1.6 on 2025-05-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_remove_announcement_school_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
