# Generated by Django 5.1.6 on 2025-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0021_delete_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
