# Generated by Django 5.1.6 on 2025-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0022_assignment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='section',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignments', to='academic.section'),
        ),
    ]
