# Generated by Django 5.1.6 on 2025-05-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0023_alter_assignment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('ng', 'Not Graded'), ('g', 'Graded')], default='ng', max_length=10),
        ),
    ]
