# Generated by Django 5.1.6 on 2025-05-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
