# Generated by Django 5.1.6 on 2025-05-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0025_submission_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
