# Generated by Django 5.1.6 on 2025-05-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0026_alter_submission_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='chat_room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.DeleteModel(
            name='ChatAttachments',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
