# Generated by Django 5.1.6 on 2025-05-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0027_remove_chatmessage_chat_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinepaymenttransaction',
            name='fees',
        ),
        migrations.DeleteModel(
            name='Fees',
        ),
        migrations.DeleteModel(
            name='OnlinePaymentTransaction',
        ),
    ]
